### ISSUE TITLE
Contour Simplification value is incorrect type

### ISSUE THREAD

**Issue by Bankst** [PhotonVision/photonvision#100]
```
[2020-08-23 13:26:35] [WebServer - SocketHandler] [DEBUG] Got WS message: [SMT_PIPELINESETTINGCHANGE] ==> [changePipelineSetting], [{cornerDetectionAccuracyPercentage=88, cameraIndex=0}]
[2020-08-23 13:26:35] [WebServer - Server] [DEBUG] Got WebSockets binary message from host /127.0.0.1:51733
[2020-08-23 13:26:35] [VisionModule - VisionModuleChangeSubscriber - WPI2020] [ERROR] Unknown exception when setting PSC prop!
[2020-08-23 13:26:35] [VisionModule - VisionModuleChangeSubscriber - WPI2020] [ERROR] java.lang.ClassCastException: class java.lang.Integer cannot be cast to class java.lang.Double (java.lang.Integer and java.lang.Double are in module java.base of loader 'bootstrap')
	at org.photonvision.vision.processes.VisionModuleChangeSubscriber.onDataChangeEvent(VisionModuleChangeSubscriber.java:172)
	at org.photonvision.common.dataflow.DataChangeService.dispatchFromQueue(DataChangeService.java:66)
	at java.base/java.lang.Thread.run(Thread.java:835)
```

**Comment by mcm001** [comment]
Fixed in master.
