### ISSUE TITLE
"videoMode" is null

### ISSUE THREAD

**Issue by Juniormunk** [PhotonVision/photonvision#1510]
[20:40:21] [2024-07-04 05:27:13] [General - TimedTaskManager] [ERROR] Exception thrown by threadpool: Cannot read field "width" because "videoMode" is null: Cannot read field "width" because "videoMode" is null
[20:40:21] [2024-07-04 05:27:13] [General - TimedTaskManager] [ERROR] java.lang.NullPointerException: Cannot read field "width" because "videoMode" is null at org.photonvision.vision.processes.VisionSourceSettables.lambda$calculateFrameStaticProps$0(VisionSourceSettables.java:121) at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178) at java.base/java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1602) at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129) at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527) at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513) at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150) at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:647) at org.photonvision.vision.processes.VisionSourceSettables.calculateFrameStaticProps(VisionSourceSettables.java:123) at org.photonvision.vision.processes.VisionSourceSettables.setVideoMode(VisionSourceSettables.java:85) at org.photonvision.vision.processes.VisionSourceSettables.setVideoModeInternal(VisionSourceSettables.java:70) at org.photonvision.vision.processes.VisionModule.setPipeline(VisionModule.java:420) at org.photonvision.vision.processes.VisionModule.<init>(VisionModule.java:159) at org.photonvision.vision.processes.VisionModuleManager.addSources(VisionModuleManager.java:63) at org.photonvision.vision.processes.VisionSourceManager.tryMatchCams(VisionSourceManager.java:119) at org.photonvision.common.util.TimedTaskManager$CaughtScheduledThreadPoolExecutor.lambda$wrap$0(TimedTaskManager.java:56) at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) at java.base/java.lang.Thread.run(Thread.java:840)

**Comment by Juniormunk** [comment]
This is just quite a weird issue cscore is able to see the camera but it is not able to connect to it so it is disconnected resulting in no available video modes
