### ISSUE TITLE
obs object in calibrationUtils.py throws an incorrect class type

### ISSUE THREAD

**Issue by elvizer** [PhotonVision/photonvision#1612]
**Describe the bug**
When running calibrationUtils.py found in the latest version of the docs, I get this error:
`AttributeError: 'Generic' object has no attribute 'snapshotData'. Did you mean: 'snapshotName'?`

However, when printing the type of `obs` in `obs.snapshotData.data`, it prints:
`<class '__main__.convert_photon_to_mrcal.<locals>.Generic'>`

When hovering over `obs` in Visual Studios Code, it says that it is of type `Observation`

**To Reproduce**
1. Download calibrationUtils.py from the latest version of PhotonVision docs, found [here.](https://raw.githubusercontent.com/PhotonVision/photonvision/master/devTools/calibrationUtils.py)
2. Run `python3 /path/to/calibrationUtils.py path/to/photon_calibration.json /path/to/output/folder` (in my case WSL).
3. See error

**Screenshots / Videos**
![image](https://github.com/user-attachments/assets/0d7d0b2e-5d1e-4394-b782-f0ab95d25a1d)
![image](https://github.com/user-attachments/assets/8478021f-998b-4b8e-bdc7-c2b2938686ed)

**Platform:**
 - Windows 10 (Version 19045.5131)
 - Ubuntu 24.04.1 LTS (WSL)
 - Visual Studios Code

**Comment by mcm001** [comment]
@Juniormunk did cal json format change over the summer? Either way I have a patched version floating around.

**Comment by Juniormunk** [comment]
Yes. We no longer store the images in the json.

**Comment by mcm001** [comment]
Maybe  https://github.com/PhotonVision/photonvision/pull/1615

**Comment by PureRandomGit** [comment]
Sadly I still get the same error as above.
```
Traceback (most recent call last):
  File "/calibrationUtils.py", line 254, in <module>
    main()
  File "/calibrationUtils.py", line 250, in main
    convert_photon_to_mrcal(args.input, args.output_folder)
  File "/calibrationUtils.py", line 210, in convert_photon_to_mrcal
    image = obs.snapshotData.data
            ^^^^^^^^^^^^^^^^
AttributeError: 'Generic' object has no attribute 'snapshotData'. Did you mean: 'snapshotName'?
```
Platform:
KDE Neon6.2
Photonvision v2025.0.0-beta-6

**Comment by Juniormunk** [comment]
@PureRandomGit  Sorry. I meant to fix this a while ago. I don't have a good way to test this code, but here are the changes. #1633

**Comment by PureRandomGit** [comment]
Thank you, it fixes that problem but I encountered two others so far.
First is this one which I bypassed by changing the json width to remove the floats
```
Traceback (most recent call last):
  File "/calibrationUtils.py", line 237, in <module>
    main()
  File "/calibrationUtils.py", line 233, in main
    convert_photon_to_mrcal(args.input, args.output_folder)
  File "/calibrationUtils.py", line 210, in convert_photon_to_mrcal
    mrcal_model = __convert_cal_to_mrcal_cameramodel(camera_cal_data)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/calibrationUtils.py", line 129, in __convert_cal_to_mrcal_cameramodel
    ).reshape((cal.calobjectSize.width, cal.calobjectSize.height, 3))
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'float' object cannot be interpreted as an integer
```
At this point it was able to generate the corners.vnl but errors when trying to reshape the array due to some of the images not getting all the points, at least I think.
```
Traceback (most recent call last):
  File "/calibrationUtils.py", line 237, in <module>
    main()
  File "/calibrationUtils.py", line 233, in main
    convert_photon_to_mrcal(args.input, args.output_folder)
  File "/calibrationUtils.py", line 210, in convert_photon_to_mrcal
    mrcal_model = __convert_cal_to_mrcal_cameramodel(camera_cal_data)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/calibrationUtils.py", line 129, in __convert_cal_to_mrcal_cameramodel
    ).reshape((cal.calobjectSize.width, cal.calobjectSize.height, 3))
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: cannot reshape array of size 135 into shape (7,7,3)
```
