### ISSUE TITLE
Infinite NPE spam after enabling 3d mode

### ISSUE THREAD

**Issue by mcm001** [PhotonVision/photonvision#1659]
**Describe the bug**

After calibrating my ov2311 and enabling 3d mode, the console gets infinitely many NPEs 
![image](https://github.com/user-attachments/assets/753e3a53-2954-4876-906c-86bcab2c8bb8)

**To Reproduce**
1. Start photon with --clear-config
2. Observe your OV2311 starts at 160x120
3. Enable the OV2311 quirk and save changes
4. Calibrate your camera at 1600x1200. My OV2311 is camera index 0 in the UI if that matters, and i used our charuco board
5. Finish calibration
6. Swap camera resolution to the calibrated resolution (for me, 1600x1200@50fps mjpg)
7. Enable 3d mode
9. Observe the above errors
10. Wait for a minute
11. observe your laptop OOMs

```
[2024-12-26 20:25:35] [VisionModule - VisionRunner - USBFrameProvider - opencv_Arducam_OV2311_USB_Camera] [ERROR] Exception on loop 3865: Cannot read field "calibration" because "this.params" is null
[2024-12-26 20:25:36] [VisionModule - VisionRunner - USBFrameProvider - opencv_Arducam_OV2311_USB_Camera] [ERROR] java.lang.NullPointerException: Cannot read field "calibration" because "this.params" is null
        at org.photonvision.vision.pipe.impl.AprilTagPoseEstimatorPipe.process(AprilTagPoseEstimatorPipe.java:57)
        at org.photonvision.vision.pipe.impl.AprilTagPoseEstimatorPipe.process(AprilTagPoseEstimatorPipe.java:31)
        at org.photonvision.vision.pipe.CVPipe.run(CVPipe.java:54)
        at org.photonvision.vision.pipeline.AprilTagPipeline.process(AprilTagPipeline.java:187)
        at org.photonvision.vision.pipeline.AprilTagPipeline.process(AprilTagPipeline.java:51)
        at org.photonvision.vision.pipeline.CVPipeline.run(CVPipeline.java:82)
        at org.photonvision.vision.processes.VisionRunner.update(VisionRunner.java:114)
        at java.base/java.lang.Thread.run(Thread.java:840)

[2024-12-26 20:25:38] [VisionModule - VisionRunner - USBFrameProvider - opencv_Arducam_OV2311_USB_Camera] [ERROR] Exception on loop 3866: Cannot read field "calibration" because "this.params" is null
[2024-12-26 20:25:40] [VisionModule - VisionRunner - USBFrameProvider - opencv_Arducam_OV2311_USB_Camera] [ERROR] java.lang.NullPointerException: Cannot read field "calibration" because "this.params" is null
        at org.photonvision.vision.pipe.impl.AprilTagPoseEstimatorPipe.process(AprilTagPoseEstimatorPipe.java:57)
        at org.photonvision.vision.pipe.impl.AprilTagPoseEstimatorPipe.process(AprilTagPoseEstimatorPipe.java:31)
        at org.photonvision.vision.pipe.CVPipe.run(CVPipe.java:54)
        at org.photonvision.vision.pipeline.AprilTagPipeline.process(AprilTagPipeline.java:187)
        at org.photonvision.vision.pipeline.AprilTagPipeline.process(AprilTagPipeline.java:51)
        at org.photonvision.vision.pipeline.CVPipeline.run(CVPipeline.java:82)
        at org.photonvision.vision.processes.VisionRunner.update(VisionRunner.java:114)
        at java.base/java.lang.Thread.run(Thread.java:840)

[2024-12-26 20:26:06] [Camera - USBFrameProvider - opencv_HP_Wide_Vision_HD_Camera] [ERROR] Error grabbing image: 
Input was empty!

> Task :photon-server:run FAILED
[Incubating] Problems report is available at: file:///home/matt/Documents/GitHub/photonvision/build/reports/problems/problems-report.html

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':photon-server:run'.
> Process 'command '/usr/lib/jvm/java-17-openjdk-amd64/bin/java'' finished with non-zero exit value 137
```

Full logs:
[photonvision-2024-12-26_08-19-11.zip](https://github.com/user-attachments/files/18257356/photonvision-2024-12-26_08-19-11.zip)

Also worth noting - importing a calibration JSON does not exhibit this bug. It's only calibration

**Comment by mcm001** [comment]
Enabling the quirk seems to be related. And printing ConfigManager.getInstance().getConfig() shows the calibration added, but the pipeline's framestaticprops still haven't been.

![image](https://github.com/user-attachments/assets/78c5d000-5bac-4274-86f5-8e92a921dc5b)

**Comment by mcm001** [comment]
It seems like calculateFrameStaticProps is never called?
![image](https://github.com/user-attachments/assets/c45531b1-2ade-4175-b252-17ae7b90d469)

**Comment by mcm001** [comment]
Looks like it's changing the arducam type that causes the settables instances to become desynced
```
[2024-12-26 21:10:56] [Camera - USBCameraSource - Arducam_OV2311_USB_Camera] [INFO] Created settables org.photonvision.vision.camera.USBCameras.GenericUSBCameraSettables@49c3f04b
[2024-12-26 21:10:56] [Camera - USBFrameProvider - opencv_Arducam_OV2311_USB_Camera] [INFO] Using settables org.photonvision.vision.camera.USBCameras.GenericUSBCameraSettables@49c3f04b
<snip>
[2024-12-26 21:11:33] [Camera - USBFrameProvider - opencv_Arducam_OV2311_USB_Camera] [INFO] Grabbing with settables org.photonvision.vision.camera.USBCameras.GenericUSBCameraSettables@49c3f04b
[2024-12-26 21:11:34] [VisionModule - VisionModuleChangeSubscriber - Arducam_OV2311_USB_Camera] [INFO] Changing camera settables setting: org.photonvision.vision.camera.USBCameras.ArduOV2311CameraSettables@766eba3f
```

**Comment by mcm001** [comment]
https://github.com/PhotonVision/photonvision/blame/00d307439cc21cbc2d1357a4b402151db29c76fd/photon-core/src/main/java/org/photonvision/vision/camera/USBCameras/USBCameraSource.java#L163 changes the Settables instance out from under the USBFrameProvider

**Comment by mcm001** [comment]
Bug appears to have been introduced by https://github.com/gerth2/photonvision/commit/dbdd6911aabc732e68160d038be5ba2d0e1dd4da
