### ISSUE TITLE
Problems installing on Debian 11

### ISSUE THREAD

**Issue by WilliamLi0623** [PhotonVision/photonvision#824]
The error message is:
Seems the opencv lib is lost.

I used the official method: [https://docs.photonvision.org/en/latest/docs/getting-started/installation/sw_install/linux-pc.html](url)

> Exception in thread "main" java.lang.UnsatisfiedLinkError: /root/.wpilib/nativecache/linux/x86-64/libopencv_java460.so.11e599ec79f2eef7e1df9681276e7064: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /root/.wpilib/nativecache/linux/x86-64/libopencv_java460.so.11e599ec79f2eef7e1df9681276e7064)
        at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)
        at java.base/java.lang.ClassLoader$NativeLibrary.load(ClassLoader.java:2445)
        at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(ClassLoader.java:2501)
        at java.base/java.lang.ClassLoader.loadLibrary0(ClassLoader.java:2700)
        at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2630)
        at java.base/java.lang.Runtime.load0(Runtime.java:768)
        at java.base/java.lang.System.load(System.java:1837)
        at edu.wpi.first.util.RuntimeLoader.loadLibrary(RuntimeLoader.java:121)
        at org.photonvision.common.util.TestUtils.loadLibraries(TestUtils.java:55)
        at org.photonvision.Main.main(Main.java:299)

**Comment by mcm001** [comment]
Looks like you're using a version of debian too old. I know we need Ubuntu 22.04, not sure which debian that corresponds to
