### ISSUE TITLE
UnsatisfiedLinkError: wrong ELF class: ELFCLASS64

### ISSUE THREAD

**Issue by infiniwave** [PhotonVision/photonvision#828]
I installed PhotonVision on Ubuntu 22.04 LTS on a Raspberry Pi 2B. systemctl spits these logs out:
```
java.lang.UnsatisfiedLinkError: /opt/photonvision/lib/libphotonlibcamera.so: /opt/photonvision/lib/libphotonlibcamera.so: wrong ELF class: ELFCLASS64 (Possible cause: can't load AARCH64 .so on a ARM platform)
    at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
    at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:388)
    at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:232)
    at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:174)
    at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2389)
    at java.base/java.lang.Runtime.load0(Runtime.java:755)
    at java.base/java.lang.System.load(System.java:1953)
    at org.photonvision.raspi.LibCameraJNI.forceLoad(LibCameraJNI.java:53)
    at org.photonvision.Main.main(Main.java:306)
```

**Comment by infiniwave** [comment]
Never mind, it's because the 2B only supports ARM, not ARM64.

**Comment by infiniwave** [comment]
Actually, I've confirmed I have the ARM32 version but it's still trying to load an ARM64 library

**Comment by infiniwave** [comment]
```
java.io.IOException: /root/.wpilib/nativecache/linux/arm32/660f4ded37dc334ec88d4a428bfc80ae/libwpiutiljni.so could not be loaded from path
        attempted to load for platform /linux/arm32/
Last Load Error:
/root/.wpilib/nativecache/linux/arm32/660f4ded37dc334ec88d4a428bfc80ae/libwpiutiljni.so: libatomic.so.1: cannot open shared object file: No such file or directory

        at edu.wpi.first.util.CombinedRuntimeLoader.loadLibrary(CombinedRuntimeLoader.java:147)
        at edu.wpi.first.util.CombinedRuntimeLoader.loadLibraries(CombinedRuntimeLoader.java:183)
        at org.photonvision.common.util.TestUtils.loadLibraries(TestUtils.java:57)
        at org.photonvision.Main.main(Main.java:299)
[2023-03-10 02:19:03] [General - Main] [INFO] Native libraries loaded.
OpenJDK Server VM warning: You have loaded library /opt/photonvision/lib/libphotonlibcamera.so which might have disabled stack guard. The VM will try to fix the stack guard now.
It's highly recommended that you fix the library with 'execstack -c <libfile>', or link it with '-z noexecstack'.
[2023-03-10 02:19:03] [Camera - LibCameraJNI] [ERROR] Couldn't load libpicam shared object
java.lang.UnsatisfiedLinkError: /opt/photonvision/lib/libphotonlibcamera.so: /opt/photonvision/lib/libphotonlibcamera.so: wrong ELF class: ELFCLASS64 (Possible cause: can't load AARCH64 .so on a ARM platform)
        at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
        at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:388)
        at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:232)
        at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:174)
        at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2389)
        at java.base/java.lang.Runtime.load0(Runtime.java:755)
        at java.base/java.lang.System.load(System.java:1953)
        at org.photonvision.raspi.LibCameraJNI.forceLoad(LibCameraJNI.java:53)
        at org.photonvision.Main.main(Main.java:306)
[2023-03-10 02:19:03] [General - Main] [INFO] Logging initialized in debug mode.
[2023-03-10 02:19:03] [General - ShellExec] [DEBUG] Executing "id -u"
[2023-03-10 02:19:03] [General - ShellExec] [DEBUG] Got exit code 0
[2023-03-10 02:19:03] [General - ShellExec] [DEBUG] Executing "cat /proc/device-tree/model"
[2023-03-10 02:19:03] [General - ShellExec] [DEBUG] Got exit code 0
[2023-03-10 02:19:03] [General - Main] [INFO] Starting PhotonVision version v2023.4.2 on Linux Raspbian 32-bit (Pi UNKNOWN)
[2023-03-10 02:19:03] [General - ConfigManager] [INFO] Loading settings...
[2023-03-10 02:19:03] [General - ConfigManager] [INFO] Hardware config does not exist! Loading defaults
Exception in thread "main" java.lang.UnsatisfiedLinkError: 'int edu.wpi.first.networktables.NetworkTablesJNI.getDefaultInstance()'
        at edu.wpi.first.networktables.NetworkTablesJNI.getDefaultInstance(Native Method)
        at edu.wpi.first.networktables.NetworkTableInstance.getDefault(NetworkTableInstance.java:113)
        at org.photonvision.common.dataflow.networktables.NetworkTablesManager.<init>(NetworkTablesManager.java:37)
        at org.photonvision.common.dataflow.networktables.NetworkTablesManager.getInstance(NetworkTablesManager.java:51)
        at org.photonvision.common.hardware.HardwareManager.<init>(HardwareManager.java:78)
        at org.photonvision.common.hardware.HardwareManager.getInstance(HardwareManager.java:65)
        at org.photonvision.Main.main(Main.java:341)
[2023-03-10 02:19:06] [General - ConfigManager] [DEBUG] Saving to disk...
[2023-03-10 02:19:06] [General - ConfigManager] [INFO] Settings saved!
```

**Comment by infiniwave** [comment]
Seems like this configuration is unsupported.
