### ISSUE TITLE
Errors in console when manually editing slider values

### ISSUE THREAD

**Issue by rzblue** [PhotonVision/photonvision#911]
Errors appear in console when you use the text box to edit a slider value.

```
[2023-09-14 19:10:37] [VisionModule - VisionModuleChangeSubscriber - Integrated_Camera] [ERROR] Failed to invoke camera settable method: setExposure: null
[2023-09-14 19:10:37] [VisionModule - VisionModuleChangeSubscriber - Integrated_Camera] [ERROR] java.lang.IllegalArgumentException
        at jdk.internal.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.photonvision.vision.processes.VisionModuleChangeSubscriber.onDataChangeEvent(VisionModuleChangeSubscriber.java:180)
        at org.photonvision.common.dataflow.DataChangeService.dispatchFromQueue(DataChangeService.java:65)
        at java.base/java.lang.Thread.run(Thread.java:833)

[2023-09-14 19:10:37] [VisionModule - VisionModuleChangeSubscriber - Integrated_Camera] [ERROR] Unknown exception when setting PSC prop!: class java.lang.String cannot be cast to class java.lang.Number (java.lang.String and java.lang.Number are in module java.base of loader 'bootstrap')
[2023-09-14 19:10:37] [VisionModule - VisionModuleChangeSubscriber - Integrated_Camera] [ERROR] java.lang.ClassCastException: class java.lang.String cannot be cast to class java.lang.Number (java.lang.String and java.lang.Number are in module java.base of loader 'bootstrap')
        at org.photonvision.vision.processes.VisionModuleChangeSubscriber.onDataChangeEvent(VisionModuleChangeSubscriber.java:204)
        at org.photonvision.common.dataflow.DataChangeService.dispatchFromQueue(DataChangeService.java:65)
        at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by srimanachanta** [comment]
Seems like Vuetify 3 removes the option for type="number" which causes a crap ton of issues, best to just always convert to numbers before the emit.
